//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.03 at 03:16:51 PM BST 
//


package com.vodafone.global.er.decoupling.binding.request.impl;

public class FindPackagesWithServiceRequestTypeImpl implements com.vodafone.global.er.decoupling.binding.request.FindPackagesWithServiceRequestType, com.sun.xml.bind.JAXBObject, com.vodafone.global.er.decoupling.binding.request.impl.runtime.UnmarshallableObject, com.vodafone.global.er.decoupling.binding.request.impl.runtime.XMLSerializable, com.vodafone.global.er.decoupling.binding.request.impl.runtime.ValidatableObject
{

    protected com.vodafone.global.er.decoupling.binding.request.RatingAttributesType _RatingAttributes;
    protected com.vodafone.global.er.decoupling.binding.request.PurchaseAttributesType _PurchaseAttributes;
    protected boolean has_PricepointUserGroupsRequired;
    protected boolean _PricepointUserGroupsRequired;
    protected java.lang.String _ServiceId;
    protected java.lang.String _Msisdn;
    protected java.lang.String _LogId;
    protected boolean has_PricepointStartEndDatesRequired;
    protected boolean _PricepointStartEndDatesRequired;
    public final static java.lang.Class version = (com.vodafone.global.er.decoupling.binding.request.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.vodafone.global.er.decoupling.binding.request.FindPackagesWithServiceRequestType.class);
    }

    public com.vodafone.global.er.decoupling.binding.request.RatingAttributesType getRatingAttributes() {
        return _RatingAttributes;
    }

    public void setRatingAttributes(com.vodafone.global.er.decoupling.binding.request.RatingAttributesType value) {
        _RatingAttributes = value;
    }

    public com.vodafone.global.er.decoupling.binding.request.PurchaseAttributesType getPurchaseAttributes() {
        return _PurchaseAttributes;
    }

    public void setPurchaseAttributes(com.vodafone.global.er.decoupling.binding.request.PurchaseAttributesType value) {
        _PurchaseAttributes = value;
    }

    public boolean isPricepointUserGroupsRequired() {
        return _PricepointUserGroupsRequired;
    }

    public void setPricepointUserGroupsRequired(boolean value) {
        _PricepointUserGroupsRequired = value;
        has_PricepointUserGroupsRequired = true;
    }

    public java.lang.String getServiceId() {
        return _ServiceId;
    }

    public void setServiceId(java.lang.String value) {
        _ServiceId = value;
    }

    public java.lang.String getMsisdn() {
        return _Msisdn;
    }

    public void setMsisdn(java.lang.String value) {
        _Msisdn = value;
    }

    public java.lang.String getLogId() {
        return _LogId;
    }

    public void setLogId(java.lang.String value) {
        _LogId = value;
    }

    public boolean isPricepointStartEndDatesRequired() {
        return _PricepointStartEndDatesRequired;
    }

    public void setPricepointStartEndDatesRequired(boolean value) {
        _PricepointStartEndDatesRequired = value;
        has_PricepointStartEndDatesRequired = true;
    }

    public com.vodafone.global.er.decoupling.binding.request.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.vodafone.global.er.decoupling.binding.request.impl.runtime.UnmarshallingContext context) {
        return new com.vodafone.global.er.decoupling.binding.request.impl.FindPackagesWithServiceRequestTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(com.vodafone.global.er.decoupling.binding.request.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "service-id");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _ServiceId), "ServiceId");
        } catch (java.lang.Exception e) {
            com.vodafone.global.er.decoupling.binding.request.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        if (_Msisdn!= null) {
            context.startElement("", "msisdn");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Msisdn), "Msisdn");
            } catch (java.lang.Exception e) {
                com.vodafone.global.er.decoupling.binding.request.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_PurchaseAttributes!= null) {
            context.startElement("", "purchase-attributes");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _PurchaseAttributes), "PurchaseAttributes");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _PurchaseAttributes), "PurchaseAttributes");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _PurchaseAttributes), "PurchaseAttributes");
            context.endElement();
        }
        if (_RatingAttributes!= null) {
            context.startElement("", "rating-attributes");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _RatingAttributes), "RatingAttributes");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _RatingAttributes), "RatingAttributes");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _RatingAttributes), "RatingAttributes");
            context.endElement();
        }
        if (has_PricepointStartEndDatesRequired) {
            context.startElement("", "pricepoint-start-end-dates-required");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printBoolean(((boolean) _PricepointStartEndDatesRequired)), "PricepointStartEndDatesRequired");
            } catch (java.lang.Exception e) {
                com.vodafone.global.er.decoupling.binding.request.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (has_PricepointUserGroupsRequired) {
            context.startElement("", "pricepoint-user-groups-required");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printBoolean(((boolean) _PricepointUserGroupsRequired)), "PricepointUserGroupsRequired");
            } catch (java.lang.Exception e) {
                com.vodafone.global.er.decoupling.binding.request.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_LogId!= null) {
            context.startElement("", "log-id");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _LogId), "LogId");
            } catch (java.lang.Exception e) {
                com.vodafone.global.er.decoupling.binding.request.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
    }

    public void serializeAttributes(com.vodafone.global.er.decoupling.binding.request.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(com.vodafone.global.er.decoupling.binding.request.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.vodafone.global.er.decoupling.binding.request.FindPackagesWithServiceRequestType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000pp"
+"sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnam"
+"eClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.gram"
+"mar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcon"
+"tentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003pp\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun.msv.grammar.DataE"
+"xp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006excep"
+"tq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003sr\u0000\u0011java."
+"lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000#com.sun.msv.datatype."
+"xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.dat"
+"atype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.dataty"
+"pe.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.X"
+"SDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;"
+"L\u0000\btypeNameq\u0000~\u0000\u001aL\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/Wh"
+"iteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0006st"
+"ringsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserv"
+"e\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expression$NullSetExpr"
+"ession\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000\u0015psr\u0000\u001bcom.sun.msv.util.StringPair"
+"\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001aL\u0000\fnamespaceURIq\u0000~\u0000\u001axpq\u0000~\u0000\u001eq\u0000~\u0000\u001d"
+"sr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 com."
+"sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameCla"
+"ssq\u0000~\u0000\fxq\u0000~\u0000\u0003q\u0000~\u0000\u0015psq\u0000~\u0000\u0010ppsr\u0000\"com.sun.msv.datatype.xsd.Qnam"
+"eType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0017q\u0000~\u0000\u001dt\u0000\u0005QNamesr\u00005com.sun.msv.datatype."
+"xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000 q\u0000~\u0000#sq\u0000~\u0000$"
+"q\u0000~\u0000-q\u0000~\u0000\u001dsr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002"
+"L\u0000\tlocalNameq\u0000~\u0000\u001aL\u0000\fnamespaceURIq\u0000~\u0000\u001axr\u0000\u001dcom.sun.msv.grammar"
+".NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLS"
+"chema-instancesr\u00000com.sun.msv.grammar.Expression$EpsilonExpr"
+"ession\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000\u0014\u0001psq\u0000~\u00001t\u0000\nservice-idt\u0000\u0000sq\u0000~\u0000&p"
+"psq\u0000~\u0000\u000bq\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0013sq\u0000~\u0000&ppsq\u0000~\u0000(q\u0000~\u0000\u0015pq\u0000~\u0000*q\u0000~\u00003q\u0000~"
+"\u00007sq\u0000~\u00001t\u0000\u0006msisdnq\u0000~\u0000;q\u0000~\u00007sq\u0000~\u0000&ppsq\u0000~\u0000\u000bq\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u0000ppsq\u0000~"
+"\u0000\u000bpp\u0000sq\u0000~\u0000&ppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003"
+"q\u0000~\u0000\u0015psq\u0000~\u0000(q\u0000~\u0000\u0015psr\u00002com.sun.msv.grammar.Expression$AnyStri"
+"ngExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u00008psr\u0000 com.sun.msv.grammar.A"
+"nyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00002q\u0000~\u00007sq\u0000~\u00001t\u0000Hcom.vodafone.globa"
+"l.er.decoupling.binding.request.PurchaseAttributesTypet\u0000+htt"
+"p://java.sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000&ppsq\u0000~\u0000(q\u0000~\u0000\u0015p"
+"q\u0000~\u0000*q\u0000~\u00003q\u0000~\u00007sq\u0000~\u00001t\u0000\u0013purchase-attributesq\u0000~\u0000;q\u0000~\u00007sq\u0000~\u0000&p"
+"psq\u0000~\u0000\u000bq\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000&ppsq\u0000~\u0000Hq\u0000~\u0000\u0015psq\u0000~\u0000(q\u0000~"
+"\u0000\u0015pq\u0000~\u0000Mq\u0000~\u0000Oq\u0000~\u00007sq\u0000~\u00001t\u0000Fcom.vodafone.global.er.decoupling"
+".binding.request.RatingAttributesTypeq\u0000~\u0000Rsq\u0000~\u0000&ppsq\u0000~\u0000(q\u0000~\u0000"
+"\u0015pq\u0000~\u0000*q\u0000~\u00003q\u0000~\u00007sq\u0000~\u00001t\u0000\u0011rating-attributesq\u0000~\u0000;q\u0000~\u00007sq\u0000~\u0000&p"
+"psq\u0000~\u0000\u000bq\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0010ppsr\u0000$com.sun.msv.datatype.xsd.B"
+"ooleanType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0017q\u0000~\u0000\u001dt\u0000\u0007booleanq\u0000~\u0000/q\u0000~\u0000#sq\u0000~\u0000$q\u0000"
+"~\u0000jq\u0000~\u0000\u001dsq\u0000~\u0000&ppsq\u0000~\u0000(q\u0000~\u0000\u0015pq\u0000~\u0000*q\u0000~\u00003q\u0000~\u00007sq\u0000~\u00001t\u0000#pricepoi"
+"nt-start-end-dates-requiredq\u0000~\u0000;q\u0000~\u00007sq\u0000~\u0000&ppsq\u0000~\u0000\u000bq\u0000~\u0000\u0015p\u0000sq"
+"\u0000~\u0000\u0000ppq\u0000~\u0000gsq\u0000~\u0000&ppsq\u0000~\u0000(q\u0000~\u0000\u0015pq\u0000~\u0000*q\u0000~\u00003q\u0000~\u00007sq\u0000~\u00001t\u0000\u001fprice"
+"point-user-groups-requiredq\u0000~\u0000;q\u0000~\u00007sq\u0000~\u0000&ppsq\u0000~\u0000\u000bq\u0000~\u0000\u0015p\u0000sq\u0000"
+"~\u0000\u0000ppq\u0000~\u0000\u0013sq\u0000~\u0000&ppsq\u0000~\u0000(q\u0000~\u0000\u0015pq\u0000~\u0000*q\u0000~\u00003q\u0000~\u00007sq\u0000~\u00001t\u0000\u0006log-id"
+"q\u0000~\u0000;q\u0000~\u00007sr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L"
+"\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPool$ClosedHash;"
+"xpsr\u0000-com.sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003"
+"\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/E"
+"xpressionPool;xp\u0000\u0000\u0000\u001e\u0001pq\u0000~\u0000Cq\u0000~\u0000<q\u0000~\u0000Wq\u0000~\u0000wq\u0000~\u0000\u000fq\u0000~\u0000>q\u0000~\u0000Jq\u0000~"
+"\u0000\\q\u0000~\u0000yq\u0000~\u0000Eq\u0000~\u0000Yq\u0000~\u0000Gq\u0000~\u0000[q\u0000~\u0000\'q\u0000~\u0000?q\u0000~\u0000Sq\u0000~\u0000`q\u0000~\u0000lq\u0000~\u0000sq\u0000~"
+"\u0000zq\u0000~\u0000\u0007q\u0000~\u0000\tq\u0000~\u0000fq\u0000~\u0000rq\u0000~\u0000\u0005q\u0000~\u0000\u0006q\u0000~\u0000\nq\u0000~\u0000\bq\u0000~\u0000dq\u0000~\u0000px"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.vodafone.global.er.decoupling.binding.request.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.vodafone.global.er.decoupling.binding.request.impl.runtime.UnmarshallingContext context) {
            super(context, "----------------------");
        }

        protected Unmarshaller(com.vodafone.global.er.decoupling.binding.request.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.vodafone.global.er.decoupling.binding.request.impl.FindPackagesWithServiceRequestTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  0 :
                        if (("service-id" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 1;
                            return ;
                        }
                        break;
                    case  3 :
                        if (("msisdn" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 4;
                            return ;
                        }
                        state = 6;
                        continue outer;
                    case  7 :
                        if (("is-repurchase" == ___local)&&("" == ___uri)) {
                            _PurchaseAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("force-reservation" == ___local)&&("" == ___uri)) {
                            _PurchaseAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("status" == ___local)&&("" == ___uri)) {
                            _PurchaseAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("start-date" == ___local)&&("" == ___uri)) {
                            _PurchaseAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("end-date" == ___local)&&("" == ___uri)) {
                            _PurchaseAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("resource-balances-only" == ___local)&&("" == ___uri)) {
                            _PurchaseAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("external-sub-id" == ___local)&&("" == ___uri)) {
                            _PurchaseAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _PurchaseAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  21 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  12 :
                        if (("pricepoint-start-end-dates-required" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 13;
                            return ;
                        }
                        state = 15;
                        continue outer;
                    case  10 :
                        if (("asset-id" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("content-name" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("device-id" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("device-type" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("payment-type" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("bearer" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("event-date-time" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("express-purchase-flag" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("is-interactive" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("promo-code" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("device-name" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("access-channel" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("duration-code" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("duration" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("payment-information" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("network-code-string" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("pre-rate" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("renewal-pre-rate" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("pre-rate-price-is-gross" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("purchase-channel" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("tax-rate" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("has-tax-rate" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("affiliate-id" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("external-field1" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("external-field2" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("external-trans-id" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("tariff" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("partner-id" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("aggregator-id" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("recipient-msisdn" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("product-code" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("merchant-name" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("invoice-text" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("channel" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("short-package-id" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("tax-code" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("charging-method" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("user-group" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("has-historic-price-point-flag" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("history-start-date" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("vendor-id" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("csr-id" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("content-category" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("partner-url" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("partner-contact-info" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("partner-email" == ___local)&&("" == ___uri)) {
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  6 :
                        if (("purchase-attributes" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 7;
                            return ;
                        }
                        state = 9;
                        continue outer;
                    case  15 :
                        if (("pricepoint-user-groups-required" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 16;
                            return ;
                        }
                        state = 18;
                        continue outer;
                    case  18 :
                        if (("log-id" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 19;
                            return ;
                        }
                        state = 21;
                        continue outer;
                    case  9 :
                        if (("rating-attributes" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 10;
                            return ;
                        }
                        state = 12;
                        continue outer;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  8 :
                        if (("purchase-attributes" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  17 :
                        if (("pricepoint-user-groups-required" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 18;
                            return ;
                        }
                        break;
                    case  3 :
                        state = 6;
                        continue outer;
                    case  7 :
                        _PurchaseAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl) spawnChildFromLeaveElement((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl.class), 8, ___uri, ___local, ___qname));
                        return ;
                    case  21 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        if (("service-id" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  12 :
                        state = 15;
                        continue outer;
                    case  10 :
                        _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromLeaveElement((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname));
                        return ;
                    case  11 :
                        if (("rating-attributes" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  5 :
                        if (("msisdn" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  20 :
                        if (("log-id" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 21;
                            return ;
                        }
                        break;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  14 :
                        if (("pricepoint-start-end-dates-required" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 15;
                            return ;
                        }
                        break;
                    case  18 :
                        state = 21;
                        continue outer;
                    case  9 :
                        state = 12;
                        continue outer;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        state = 6;
                        continue outer;
                    case  7 :
                        _PurchaseAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl) spawnChildFromEnterAttribute((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl.class), 8, ___uri, ___local, ___qname));
                        return ;
                    case  21 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  12 :
                        state = 15;
                        continue outer;
                    case  10 :
                        _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromEnterAttribute((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname));
                        return ;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  18 :
                        state = 21;
                        continue outer;
                    case  9 :
                        state = 12;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        state = 6;
                        continue outer;
                    case  7 :
                        _PurchaseAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl) spawnChildFromLeaveAttribute((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl.class), 8, ___uri, ___local, ___qname));
                        return ;
                    case  21 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  12 :
                        state = 15;
                        continue outer;
                    case  10 :
                        _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromLeaveAttribute((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, ___uri, ___local, ___qname));
                        return ;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  18 :
                        state = 21;
                        continue outer;
                    case  9 :
                        state = 12;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  19 :
                            state = 20;
                            eatText1(value);
                            return ;
                        case  1 :
                            state = 2;
                            eatText2(value);
                            return ;
                        case  3 :
                            state = 6;
                            continue outer;
                        case  4 :
                            state = 5;
                            eatText3(value);
                            return ;
                        case  7 :
                            _PurchaseAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl) spawnChildFromText((com.vodafone.global.er.decoupling.binding.request.impl.PurchaseAttributesTypeImpl.class), 8, value));
                            return ;
                        case  21 :
                            revertToParentFromText(value);
                            return ;
                        case  12 :
                            state = 15;
                            continue outer;
                        case  10 :
                            _RatingAttributes = ((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl) spawnChildFromText((com.vodafone.global.er.decoupling.binding.request.impl.RatingAttributesTypeImpl.class), 11, value));
                            return ;
                        case  6 :
                            state = 9;
                            continue outer;
                        case  15 :
                            state = 18;
                            continue outer;
                        case  18 :
                            state = 21;
                            continue outer;
                        case  13 :
                            state = 14;
                            eatText4(value);
                            return ;
                        case  9 :
                            state = 12;
                            continue outer;
                        case  16 :
                            state = 17;
                            eatText5(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _LogId = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _ServiceId = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Msisdn = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _PricepointStartEndDatesRequired = javax.xml.bind.DatatypeConverter.parseBoolean(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_PricepointStartEndDatesRequired = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText5(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _PricepointUserGroupsRequired = javax.xml.bind.DatatypeConverter.parseBoolean(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_PricepointUserGroupsRequired = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
