//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.03 at 03:16:51 PM BST 
//


package com.vodafone.global.er.decoupling.binding.request;


/**
 * Java content class for drmTypeFullType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/matt/workspace/manifest-work/us/dev/er_core_batch_matt/working/DECOUPLING_common/schemas/common/pa_common.xsd line 1372)
 * <p>
 * <pre>
 * &lt;complexType name="drmTypeFullType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="is-drm" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="is-jdp" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface DrmTypeFullType {


    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getName();

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setName(java.lang.String value);

    /**
     * Gets the value of the isJdp property.
     * 
     */
    boolean isIsJdp();

    /**
     * Sets the value of the isJdp property.
     * 
     */
    void setIsJdp(boolean value);

    /**
     * Gets the value of the code property.
     * 
     */
    int getCode();

    /**
     * Sets the value of the code property.
     * 
     */
    void setCode(int value);

    /**
     * Gets the value of the isDrm property.
     * 
     */
    boolean isIsDrm();

    /**
     * Sets the value of the isDrm property.
     * 
     */
    void setIsDrm(boolean value);

}
