////
//// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
//// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//// Any modifications to this file will be lost upon recompilation of the source schema. 
//// Generated on: 2012.09.21 at 11:53:21 AM BST 
////
//
//
//package com.vodafone.global.er.decoupling.binding.request;
//
//
///**
// * Java content class for EventInstance complex type.
// * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/morrowa/dev/tools/assembler/manifest-work/us/dev/er_core_batch/working/APPLICATION_er_decoupling/webapp/er_decoupling/schemas/input/VolumeModelRating.xsd line 17)
// * <p>
// * <pre>
// * &lt;complexType name="EventInstance">
// *   &lt;complexContent>
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *       &lt;sequence>
// *         &lt;element name="metalist" type="{http://catalog.alternate.business.ecommerce.vizzavi.com}MetaData" maxOccurs="unbounded"/>
// *       &lt;/sequence>
// *       &lt;attribute name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" />
// *       &lt;attribute name="eventvolume" type="{http://www.w3.org/2001/XMLSchema}int" />
// *     &lt;/restriction>
// *   &lt;/complexContent>
// * &lt;/complexType>
// * </pre>
// * 
// */
//public interface EventInstance {
//
//
//    /**
//     * Gets the value of the eventName property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link java.lang.String}
//     */
//    java.lang.String getEventName();
//
//    /**
//     * Sets the value of the eventName property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link java.lang.String}
//     */
//    void setEventName(java.lang.String value);
//
//    /**
//     * Gets the value of the Metalist property.
//     * 
//     * <p>
//     * This accessor method returns a reference to the live list,
//     * not a snapshot. Therefore any modification you make to the
//     * returned list will be present inside the JAXB object.
//     * This is why there is not a <CODE>set</CODE> method for the Metalist property.
//     * 
//     * <p>
//     * For example, to add a new item, do as follows:
//     * <pre>
//     *    getMetalist().add(newItem);
//     * </pre>
//     * 
//     * 
//     * <p>
//     * Objects of the following type(s) are allowed in the list
//     * {@link com.vodafone.global.er.decoupling.binding.request.MetaData}
//     * 
//     */
//    java.util.List getMetalist();
//
//    /**
//     * Gets the value of the eventvolume property.
//     * 
//     */
//    int getEventvolume();
//
//    /**
//     * Sets the value of the eventvolume property.
//     * 
//     */
//    void setEventvolume(int value);
//
//}
