//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.03 at 03:16:51 PM BST 
//


package com.vodafone.global.er.decoupling.binding.request;


/**
 * Java content class for super-credit-price-pointType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/matt/workspace/manifest-work/us/dev/er_core_batch_matt/working/DECOUPLING_common/schemas/common/pa_common.xsd line 109)
 * <p>
 * <pre>
 * &lt;complexType name="super-credit-price-pointType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rate-identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="super-credit-text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="is-active" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="discount-promo-text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="net-rate" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="pricing-text-1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pricing-text-2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="standard-rate" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="standard-rate-as-string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="price-point-id-link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="purchase-link-text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="promo-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fixed-expiry-date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="is-preview" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="is-pre-order" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="is-trial" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="is-discount" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="is-recurring-package" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="interactive-flag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="drm-object" type="{http://localhost:8080/decoupling/schemas/common}drm-objectType"/>
 *         &lt;element name="charging-resource" type="{http://localhost:8080/decoupling/schemas/common}charging-resourceType"/>
 *         &lt;element name="is-valid-super-credit-option" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="rate-as-string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="roaming-net-amount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="roaming-gross-amount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="roaming-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface SuperCreditPricePointType {


    /**
     * Gets the value of the purchaseLinkText property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getPurchaseLinkText();

    /**
     * Sets the value of the purchaseLinkText property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setPurchaseLinkText(java.lang.String value);

    /**
     * Gets the value of the roamingGrossAmount property.
     * 
     */
    double getRoamingGrossAmount();

    /**
     * Sets the value of the roamingGrossAmount property.
     * 
     */
    void setRoamingGrossAmount(double value);

    /**
     * Gets the value of the isValidSuperCreditOption property.
     * 
     */
    boolean isIsValidSuperCreditOption();

    /**
     * Sets the value of the isValidSuperCreditOption property.
     * 
     */
    void setIsValidSuperCreditOption(boolean value);

    /**
     * Gets the value of the isDiscount property.
     * 
     */
    boolean isIsDiscount();

    /**
     * Sets the value of the isDiscount property.
     * 
     */
    void setIsDiscount(boolean value);

    /**
     * Gets the value of the interactiveFlag property.
     * 
     */
    boolean isInteractiveFlag();

    /**
     * Sets the value of the interactiveFlag property.
     * 
     */
    void setInteractiveFlag(boolean value);

    /**
     * Gets the value of the standardRateAsString property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getStandardRateAsString();

    /**
     * Sets the value of the standardRateAsString property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setStandardRateAsString(java.lang.String value);

    /**
     * Gets the value of the pricePointIdLink property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getPricePointIdLink();

    /**
     * Sets the value of the pricePointIdLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setPricePointIdLink(java.lang.String value);

    /**
     * Gets the value of the isRecurringPackage property.
     * 
     */
    boolean isIsRecurringPackage();

    /**
     * Sets the value of the isRecurringPackage property.
     * 
     */
    void setIsRecurringPackage(boolean value);

    /**
     * Gets the value of the isActive property.
     * 
     */
    boolean isIsActive();

    /**
     * Sets the value of the isActive property.
     * 
     */
    void setIsActive(boolean value);

    /**
     * Gets the value of the isTrial property.
     * 
     */
    boolean isIsTrial();

    /**
     * Sets the value of the isTrial property.
     * 
     */
    void setIsTrial(boolean value);

    /**
     * Gets the value of the roamingNetAmount property.
     * 
     */
    double getRoamingNetAmount();

    /**
     * Sets the value of the roamingNetAmount property.
     * 
     */
    void setRoamingNetAmount(double value);

    /**
     * Gets the value of the rateAsString property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getRateAsString();

    /**
     * Sets the value of the rateAsString property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setRateAsString(java.lang.String value);

    /**
     * Gets the value of the promoCode property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getPromoCode();

    /**
     * Sets the value of the promoCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setPromoCode(java.lang.String value);

    /**
     * Gets the value of the superCreditText property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getSuperCreditText();

    /**
     * Sets the value of the superCreditText property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setSuperCreditText(java.lang.String value);

    /**
     * Gets the value of the netRate property.
     * 
     */
    double getNetRate();

    /**
     * Sets the value of the netRate property.
     * 
     */
    void setNetRate(double value);

    /**
     * Gets the value of the fixedExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.util.Calendar}
     */
    java.util.Calendar getFixedExpiryDate();

    /**
     * Sets the value of the fixedExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.util.Calendar}
     */
    void setFixedExpiryDate(java.util.Calendar value);

    /**
     * Gets the value of the rateIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getRateIdentifier();

    /**
     * Sets the value of the rateIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setRateIdentifier(java.lang.String value);

    /**
     * Gets the value of the roamingType property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getRoamingType();

    /**
     * Sets the value of the roamingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setRoamingType(java.lang.String value);

    /**
     * Gets the value of the chargingResource property.
     * 
     * @return
     *     possible object is
     *     {@link com.vodafone.global.er.decoupling.binding.request.ChargingResourceType}
     */
    com.vodafone.global.er.decoupling.binding.request.ChargingResourceType getChargingResource();

    /**
     * Sets the value of the chargingResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.vodafone.global.er.decoupling.binding.request.ChargingResourceType}
     */
    void setChargingResource(com.vodafone.global.er.decoupling.binding.request.ChargingResourceType value);

    /**
     * Gets the value of the drmObject property.
     * 
     * @return
     *     possible object is
     *     {@link com.vodafone.global.er.decoupling.binding.request.DrmObjectType}
     */
    com.vodafone.global.er.decoupling.binding.request.DrmObjectType getDrmObject();

    /**
     * Sets the value of the drmObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.vodafone.global.er.decoupling.binding.request.DrmObjectType}
     */
    void setDrmObject(com.vodafone.global.er.decoupling.binding.request.DrmObjectType value);

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getId();

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setId(java.lang.String value);

    /**
     * Gets the value of the isPreview property.
     * 
     */
    boolean isIsPreview();

    /**
     * Sets the value of the isPreview property.
     * 
     */
    void setIsPreview(boolean value);

    /**
     * Gets the value of the standardRate property.
     * 
     */
    double getStandardRate();

    /**
     * Sets the value of the standardRate property.
     * 
     */
    void setStandardRate(double value);

    /**
     * Gets the value of the pricingText1 property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getPricingText1();

    /**
     * Sets the value of the pricingText1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setPricingText1(java.lang.String value);

    /**
     * Gets the value of the pricingText2 property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getPricingText2();

    /**
     * Sets the value of the pricingText2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setPricingText2(java.lang.String value);

    /**
     * Gets the value of the discountPromoText property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getDiscountPromoText();

    /**
     * Sets the value of the discountPromoText property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setDiscountPromoText(java.lang.String value);

    /**
     * Gets the value of the isPreOrder property.
     * 
     */
    boolean isIsPreOrder();

    /**
     * Sets the value of the isPreOrder property.
     * 
     */
    void setIsPreOrder(boolean value);

}
