//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.13 at 04:57:40 PM BST 
//


package com.vodafone.global.er.decoupling.binding.response.impl;

public class UsageAuthorisationImpl
    extends com.vodafone.global.er.decoupling.binding.response.impl.UsageAuthorisationTypeImpl
    implements com.vodafone.global.er.decoupling.binding.response.UsageAuthorisation, com.sun.xml.bind.RIElement, com.sun.xml.bind.JAXBObject, com.vodafone.global.er.decoupling.binding.response.impl.runtime.UnmarshallableObject, com.vodafone.global.er.decoupling.binding.response.impl.runtime.XMLSerializable, com.vodafone.global.er.decoupling.binding.response.impl.runtime.ValidatableObject
{

    public final static java.lang.Class version = (com.vodafone.global.er.decoupling.binding.response.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.vodafone.global.er.decoupling.binding.response.UsageAuthorisation.class);
    }

    public java.lang.String ____jaxb_ri____getNamespaceURI() {
        return "";
    }

    public java.lang.String ____jaxb_ri____getLocalName() {
        return "usage-authorisation";
    }

    public com.vodafone.global.er.decoupling.binding.response.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.vodafone.global.er.decoupling.binding.response.impl.runtime.UnmarshallingContext context) {
        return new com.vodafone.global.er.decoupling.binding.response.impl.UsageAuthorisationImpl.Unmarshaller(context);
    }

    public void serializeBody(com.vodafone.global.er.decoupling.binding.response.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "usage-authorisation");
        super.serializeURIs(context);
        context.endNamespaceDecls();
        super.serializeAttributes(context);
        context.endAttributes();
        super.serializeBody(context);
        context.endElement();
    }

    public void serializeAttributes(com.vodafone.global.er.decoupling.binding.response.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(com.vodafone.global.er.decoupling.binding.response.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.vodafone.global.er.decoupling.binding.response.UsageAuthorisation.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
+"\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv."
+"grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000"
+"\fcontentModelt\u0000 Lcom/sun/msv/grammar/Expression;xr\u0000\u001ecom.sun."
+"msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Lj"
+"ava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0003xppp\u0000sr\u0000\u001fcom.sun.msv.gra"
+"mmar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.BinaryExp"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1q\u0000~\u0000\u0003L\u0000\u0004exp2q\u0000~\u0000\u0003xq\u0000~\u0000\u0004ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007pps"
+"q\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000"
+"\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007pps"
+"q\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsr\u0000\u001bcom.sun.msv.grammar.Data"
+"Exp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exce"
+"ptq\u0000~\u0000\u0003L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0004ppsr\u0000$co"
+"m.sun.msv.datatype.xsd.BooleanType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv"
+".datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.da"
+"tatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.x"
+"sd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/Str"
+"ing;L\u0000\btypeNameq\u0000~\u0000\'L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xs"
+"d/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat"
+"\u0000\u0007booleansr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Co"
+"llapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProc"
+"essor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expression$NullSet"
+"Expression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z"
+"\u0000\u0005valuexp\u0000psr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tloca"
+"lNameq\u0000~\u0000\'L\u0000\fnamespaceURIq\u0000~\u0000\'xpq\u0000~\u0000+q\u0000~\u0000*sr\u0000\u001dcom.sun.msv.gr"
+"ammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\bppsr\u0000 com.sun.msv.grammar.At"
+"tributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0003L\u0000\tnameClassq\u0000~\u0000\u0001xq\u0000~\u0000\u0004q\u0000~\u00002"
+"psq\u0000~\u0000\u001fppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq"
+"\u0000~\u0000$q\u0000~\u0000*t\u0000\u0005QNameq\u0000~\u0000.q\u0000~\u00000sq\u0000~\u00003q\u0000~\u0000<q\u0000~\u0000*sr\u0000#com.sun.msv.g"
+"rammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\'L\u0000\fnamespa"
+"ceURIq\u0000~\u0000\'xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004t"
+"ypet\u0000)http://www.w3.org/2001/XMLSchema-instancesr\u00000com.sun.m"
+"sv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004sq\u0000~"
+"\u00001\u0001psq\u0000~\u0000>t\u0000\u0010is-reserved-onlyt\u0000\u0000sq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000\"sq\u0000~\u00005"
+"ppsq\u0000~\u00007q\u0000~\u00002pq\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000\u000binteractiveq\u0000~\u0000Hsq\u0000~\u0000\u0000"
+"pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000\"sq\u0000~\u00005ppsq\u0000~\u00007q\u0000~\u00002pq\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000\n"
+"is-successq\u0000~\u0000Hsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u00005ppsr\u0000 com.sun"
+".msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar."
+"UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0003xq\u0000~\u0000\u0004q\u0000~\u00002psq\u0000~\u00007q\u0000~\u00002psr\u00002co"
+"m.sun.msv.grammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000x"
+"q\u0000~\u0000\u0004q\u0000~\u0000Epsr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq"
+"\u0000~\u0000?q\u0000~\u0000Dsq\u0000~\u0000>t\u0000>com.vodafone.global.er.decoupling.binding."
+"response.PackageTypet\u0000+http://java.sun.com/jaxb/xjc/dummy-el"
+"ementssq\u0000~\u00005ppsq\u0000~\u00007q\u0000~\u00002pq\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000\u0007packageq\u0000~"
+"\u0000Hsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u00005ppsq\u0000~\u0000Yq\u0000~\u00002psq\u0000~\u00007q\u0000~\u00002p"
+"q\u0000~\u0000^q\u0000~\u0000`q\u0000~\u0000Dsq\u0000~\u0000>t\u0000Acom.vodafone.global.er.decoupling.bi"
+"nding.response.PricePointTypeq\u0000~\u0000csq\u0000~\u00005ppsq\u0000~\u00007q\u0000~\u00002pq\u0000~\u00009q"
+"\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000\u000bprice-pointq\u0000~\u0000Hsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000"
+"sq\u0000~\u00005ppsq\u0000~\u0000Yq\u0000~\u00002psq\u0000~\u00007q\u0000~\u00002pq\u0000~\u0000^q\u0000~\u0000`q\u0000~\u0000Dsq\u0000~\u0000>q\u0000~\u0000oq\u0000"
+"~\u0000csq\u0000~\u00005ppsq\u0000~\u00007q\u0000~\u00002pq\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000\u0013service-price"
+"-pointq\u0000~\u0000Hsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u00005ppsq\u0000~\u0000Yq\u0000~\u00002psq\u0000"
+"~\u00007q\u0000~\u00002pq\u0000~\u0000^q\u0000~\u0000`q\u0000~\u0000Dsq\u0000~\u0000>t\u0000Fcom.vodafone.global.er.deco"
+"upling.binding.response.ResourceBalanceTypeq\u0000~\u0000csq\u0000~\u00005ppsq\u0000~"
+"\u00007q\u0000~\u00002pq\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000\u0015user-resource-balanceq\u0000~\u0000Hsq"
+"\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u001fq\u0000~\u00002psr\u0000#com.sun.msv.datatype.xsd.Stri"
+"ngType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxq\u0000~\u0000$q\u0000~\u0000*t\u0000\u0006stringsr\u00005com"
+".sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0000xq\u0000~\u0000-\u0001q\u0000~\u00000sq\u0000~\u00003q\u0000~\u0000\u0090q\u0000~\u0000*sq\u0000~\u00005ppsq\u0000~\u00007q\u0000~\u00002pq\u0000~\u00009q\u0000~\u0000@q"
+"\u0000~\u0000Dsq\u0000~\u0000>t\u0000\u0017package-subscription-idq\u0000~\u0000Hsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq"
+"\u0000~\u0000\u0000pp\u0000sq\u0000~\u00005ppsq\u0000~\u0000Yq\u0000~\u00002psq\u0000~\u00007q\u0000~\u00002pq\u0000~\u0000^q\u0000~\u0000`q\u0000~\u0000Dsq\u0000~\u0000>"
+"t\u0000Acom.vodafone.global.er.decoupling.binding.response.Reason"
+"CodeTypeq\u0000~\u0000csq\u0000~\u00005ppsq\u0000~\u00007q\u0000~\u00002pq\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000\u000brea"
+"son-codeq\u0000~\u0000Hsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u00005ppsq\u0000~\u0000Yq\u0000~\u00002ps"
+"q\u0000~\u00007q\u0000~\u00002pq\u0000~\u0000^q\u0000~\u0000`q\u0000~\u0000Dsq\u0000~\u0000>q\u0000~\u0000\u009fq\u0000~\u0000csq\u0000~\u00005ppsq\u0000~\u00007q\u0000~\u0000"
+"2pq\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000\u000fsub-reason-codeq\u0000~\u0000Hsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000"
+"\u0007ppsq\u0000~\u0000\u001fppsr\u0000#com.sun.msv.datatype.xsd.DoubleType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0000xr\u0000+com.sun.msv.datatype.xsd.FloatingNumberType\u00fc\u00e3\u00b6\u0087\u008c\u00a8|\u00e0\u0002\u0000\u0000x"
+"q\u0000~\u0000$q\u0000~\u0000*t\u0000\u0006doubleq\u0000~\u0000.q\u0000~\u00000sq\u0000~\u00003q\u0000~\u0000\u00b5q\u0000~\u0000*sq\u0000~\u00005ppsq\u0000~\u00007q"
+"\u0000~\u00002pq\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000 receipting-credit-balance-impac"
+"tq\u0000~\u0000Hsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u001fppsr\u0000 com.sun.msv.datatype.xsd."
+"IntType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+com.sun.msv.datatype.xsd.IntegerDerive"
+"dType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nbaseFacetst\u0000)Lcom/sun/msv/datatype/xsd/XS"
+"DatatypeImpl;xq\u0000~\u0000$q\u0000~\u0000*t\u0000\u0003intq\u0000~\u0000.sr\u0000*com.sun.msv.datatype."
+"xsd.MaxInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun.msv.datatype.xsd"
+".RangeFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nlimitValuet\u0000\u0012Ljava/lang/Object;xr\u00009"
+"com.sun.msv.datatype.xsd.DataTypeWithValueConstraintFacet\"\u00a7R"
+"o\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needValueCheckFlagL\u0000\bbaseTypeq\u0000~\u0000\u00c0L\u0000\f"
+"concreteTypet\u0000\'Lcom/sun/msv/datatype/xsd/ConcreteType;L\u0000\tfac"
+"etNameq\u0000~\u0000\'xq\u0000~\u0000&ppq\u0000~\u0000.\u0000\u0001sr\u0000*com.sun.msv.datatype.xsd.MinIn"
+"clusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u00c4ppq\u0000~\u0000.\u0000\u0000sr\u0000!com.sun.msv.dataty"
+"pe.xsd.LongType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u00bfq\u0000~\u0000*t\u0000\u0004longq\u0000~\u0000.sq\u0000~\u0000\u00c3ppq\u0000~"
+"\u0000.\u0000\u0001sq\u0000~\u0000\u00cappq\u0000~\u0000.\u0000\u0000sr\u0000$com.sun.msv.datatype.xsd.IntegerType\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u00bfq\u0000~\u0000*t\u0000\u0007integerq\u0000~\u0000.sr\u0000,com.sun.msv.datatype"
+".xsd.FractionDigitsFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005scalexr\u0000;com.sun.msv.d"
+"atatype.xsd.DataTypeWithLexicalConstraintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000"
+"~\u0000\u00c7ppq\u0000~\u0000.\u0001\u0000sr\u0000#com.sun.msv.datatype.xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0000xq\u0000~\u0000$q\u0000~\u0000*t\u0000\u0007decimalq\u0000~\u0000.q\u0000~\u0000\u00d8t\u0000\u000efractionDigits\u0000\u0000\u0000\u0000q\u0000~\u0000\u00d2t"
+"\u0000\fminInclusivesr\u0000\u000ejava.lang.Long;\u008b\u00e4\u0090\u00cc\u008f#\u00df\u0002\u0000\u0001J\u0000\u0005valuexr\u0000\u0010java."
+"lang.Number\u0086\u00ac\u0095\u001d\u000b\u0094\u00e0\u008b\u0002\u0000\u0000xp\u0080\u0000\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u0000\u00d2t\u0000\fmaxInclusivesq\u0000~\u0000\u00dc\u007f\u00ff"
+"\u00ff\u00ff\u00ff\u00ff\u00ff\u00ffq\u0000~\u0000\u00cdq\u0000~\u0000\u00dbsr\u0000\u0011java.lang.Integer\u0012\u00e2\u00a0\u00a4\u00f7\u0081\u00878\u0002\u0000\u0001I\u0000\u0005valuexq\u0000~"
+"\u0000\u00dd\u0080\u0000\u0000\u0000q\u0000~\u0000\u00cdq\u0000~\u0000\u00dfsq\u0000~\u0000\u00e1\u007f\u00ff\u00ff\u00ffq\u0000~\u00000sq\u0000~\u00003q\u0000~\u0000\u00c2q\u0000~\u0000*sq\u0000~\u00005ppsq\u0000~\u0000"
+"7q\u0000~\u00002pq\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000\u001freceipting-usage-type-attribu"
+"teq\u0000~\u0000Hsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000\u008dsq\u0000~\u00005ppsq\u0000~\u00007q\u0000~\u00002pq\u0000~\u00009q\u0000~\u0000@q"
+"\u0000~\u0000Dsq\u0000~\u0000>t\u0000\u000etransaction-idq\u0000~\u0000Hsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000\"sq\u0000~\u00005"
+"ppsq\u0000~\u00007q\u0000~\u00002pq\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000\u001eis-successful-express-"
+"purchaseq\u0000~\u0000Hsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000\u00b1sq\u0000~\u00005ppsq\u0000~\u00007q\u0000~\u00002pq\u0000~\u00009"
+"q\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000\u0004rateq\u0000~\u0000Hsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u00005"
+"ppsq\u0000~\u0000Yq\u0000~\u00002psq\u0000~\u00007q\u0000~\u00002pq\u0000~\u0000^q\u0000~\u0000`q\u0000~\u0000Dsq\u0000~\u0000>t\u0000@com.vodafo"
+"ne.global.er.decoupling.binding.response.DrmObjectTypeq\u0000~\u0000cs"
+"q\u0000~\u00005ppsq\u0000~\u00007q\u0000~\u00002pq\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000\ndrm-objectq\u0000~\u0000Hsq"
+"\u0000~\u00005ppsq\u0000~\u0000\u0000q\u0000~\u00002p\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000\u008dsq\u0000~\u00005ppsq\u0000~\u00007q\u0000~\u00002pq\u0000~\u00009q\u0000~"
+"\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000\u0011error-descriptionq\u0000~\u0000Hq\u0000~\u0000Dsq\u0000~\u00005ppsq\u0000~\u0000\u0000q\u0000~"
+"\u00002p\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000\u008dsq\u0000~\u00005ppsq\u0000~\u00007q\u0000~\u00002pq\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000"
+"\berror-idq\u0000~\u0000Hq\u0000~\u0000Dsq\u0000~\u00005ppsq\u0000~\u0000\u0000q\u0000~\u00002p\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000"
+"~\u00005ppsq\u0000~\u0000Yq\u0000~\u00002psq\u0000~\u00007q\u0000~\u00002pq\u0000~\u0000^q\u0000~\u0000`q\u0000~\u0000Dsq\u0000~\u0000>t\u0000Dcom.vod"
+"afone.global.er.decoupling.binding.response.PaymentStatusTyp"
+"eq\u0000~\u0000csq\u0000~\u00005ppsq\u0000~\u00007q\u0000~\u00002pq\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000\u000epayment-st"
+"atusq\u0000~\u0000Hq\u0000~\u0000Dsq\u0000~\u00005ppsq\u0000~\u0000\u0000q\u0000~\u00002p\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000\u00bdsq\u0000~\u00005ppsq\u0000~"
+"\u00007q\u0000~\u00002pq\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000\bre-issueq\u0000~\u0000Hq\u0000~\u0000Dsq\u0000~\u00005ppsq"
+"\u0000~\u00007q\u0000~\u00002pq\u0000~\u00009q\u0000~\u0000@q\u0000~\u0000Dsq\u0000~\u0000>t\u0000\u0013usage-authorisationq\u0000~\u0000Hsr"
+"\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000"
+"/Lcom/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.su"
+"n.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000"
+"\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/ExpressionPoo"
+"l;xp\u0000\u0000\u0000Q\u0001pq\u0000~\u0000\u0014q\u0000~\u0000\u001bq\u0000~\u0000\fq\u0000~\u0001\u0007q\u0000~\u0001\u000eq\u0000~\u0000\u00a7q\u0000~\u0000\u009bq\u0000~\u0000\u0082q\u0000~\u0000wq\u0000~\u0000k"
+"q\u0000~\u0000Xq\u0000~\u0000\u00feq\u0000~\u0000\u00bcq\u0000~\u0001\u0019q\u0000~\u0001$q\u0000~\u0000\u001cq\u0000~\u0001\u0015q\u0000~\u0000\u001aq\u0000~\u0000\u0016q\u0000~\u0000\u001eq\u0000~\u0000\u00f0q\u0000~\u0000P"
+"q\u0000~\u0000\u0010q\u0000~\u0000Jq\u0000~\u0000\u0017q\u0000~\u0000\nq\u0000~\u0000\tq\u0000~\u0001\"q\u0000~\u0000\u00eaq\u0000~\u0000\u008cq\u0000~\u0001\tq\u0000~\u0001\u0010q\u0000~\u0000\u00a5q\u0000~\u0000\u00f7"
+"q\u0000~\u0000\u00f1q\u0000~\u0000\u00ebq\u0000~\u0000\u00e5q\u0000~\u0000\u00b7q\u0000~\u0000\u00abq\u0000~\u0000\u00a0q\u0000~\u0000\u0094q\u0000~\u0000\u0087q\u0000~\u0000{q\u0000~\u0000pq\u0000~\u0000dq\u0000~\u0000Q"
+"q\u0000~\u0000Kq\u0000~\u00006q\u0000~\u0000\u0099q\u0000~\u0000\u0080q\u0000~\u0000uq\u0000~\u0000iq\u0000~\u0000Vq\u0000~\u0000\u0012q\u0000~\u0001\u0003q\u0000~\u0000\u0015q\u0000~\u0000\u00fcq\u0000~\u0001\n"
+"q\u0000~\u0001\u0011q\u0000~\u0001\u001eq\u0000~\u0001\u0017q\u0000~\u0001%q\u0000~\u0001)q\u0000~\u0000\rq\u0000~\u0000lq\u0000~\u0000[q\u0000~\u0000\u00ffq\u0000~\u0000\u00a8q\u0000~\u0000\u009cq\u0000~\u0000\u0083"
+"q\u0000~\u0000xq\u0000~\u0001\u001aq\u0000~\u0000\u0011q\u0000~\u0000\u000eq\u0000~\u0000\u0019q\u0000~\u0000\u0018q\u0000~\u0000\u0013q\u0000~\u0000\u000bq\u0000~\u0000\u00f6q\u0000~\u0000\u00b0q\u0000~\u0000\u000fx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.vodafone.global.er.decoupling.binding.response.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.vodafone.global.er.decoupling.binding.response.impl.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(com.vodafone.global.er.decoupling.binding.response.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.vodafone.global.er.decoupling.binding.response.impl.UsageAuthorisationImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  0 :
                        if (("usage-authorisation" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                    case  1 :
                        if (("is-reserved-only" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.vodafone.global.er.decoupling.binding.response.impl.UsageAuthorisationTypeImpl)com.vodafone.global.er.decoupling.binding.response.impl.UsageAuthorisationImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        if (("usage-authorisation" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
