//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.13 at 04:57:40 PM BST 
//


package com.vodafone.global.er.decoupling.binding.response;


/**
 * Java content class for get-details-for-external-subscription-response element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/matt/workspace/manifest-work/us/dev/er_core_batch/working/DECOUPLING_common/schemas/response/partner_response.xsd line 27)
 * <p>
 * <pre>
 * &lt;element name="get-details-for-external-subscription-response">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="msisdn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="er-subscription-id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *             &lt;element name="end-date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *             &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *             &lt;element name="package-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;/sequence>
 *           &lt;element name="reason-code" type="{http://localhost:8080/decoupling/schemas/common}reason-codeType"/>
 *         &lt;/choice>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface GetDetailsForExternalSubscriptionResponse
    extends javax.xml.bind.Element, com.vodafone.global.er.decoupling.binding.response.GetDetailsForExternalSubscriptionResponseType
{


}
