//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.13 at 04:57:40 PM BST 
//


package com.vodafone.global.er.decoupling.binding.response;


/**
 * Java content class for onestep-packages element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/matt/workspace/manifest-work/us/dev/er_core_batch/working/DECOUPLING_common/schemas/response/response.xsd line 129)
 * <p>
 * <pre>
 * &lt;element name="onestep-packages">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="onestep-package" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="price-text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="credits-left" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="subscription-end-date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="is-subscribed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                     &lt;element name="is-express-package" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                     &lt;element name="has-purchases-options" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;/sequence>
 *                   &lt;attribute name="service-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface OnestepPackages
    extends javax.xml.bind.Element, com.vodafone.global.er.decoupling.binding.response.OnestepPackagesType
{


}
