//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.13 at 04:57:40 PM BST 
//


package com.vodafone.global.er.decoupling.binding.response;


/**
 * Java content class for subscriptionFullType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/matt/workspace/manifest-work/us/dev/er_core_batch/working/DECOUPLING_common/schemas/common/pa_common.xsd line 1241)
 * <p>
 * <pre>
 * &lt;complexType name="subscriptionFullType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="package" type="{http://localhost:8080/decoupling/schemas/common}catalogPackageFullType"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="start-date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="purchase-date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="expiry-date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="local-start-date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="local-purchase-date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="local-expiry-date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="has-expired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="resource-balances">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="resource-balance" type="{http://localhost:8080/decoupling/schemas/common}resourceBalanceFullType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="is-recurring" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="translated-status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rating-attributes" type="{http://localhost:8080/decoupling/schemas/common}ratingAttributesFullType"/>
 *         &lt;element name="final-min-subscription-end-date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="current-number-of-occurences" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="min-subscription-period-elapsed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="is-preordered" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="transactions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="transaction" type="{http://localhost:8080/decoupling/schemas/common}transactionFullType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="super-credit-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="translated-super-credit-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="super-credit-balances" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="resource-balance" type="{http://localhost:8080/decoupling/schemas/common}resourceBalanceFullType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="overdue-expiry-date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="has-valid-micro-service" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="services" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="service-id" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="disallow-cancellations" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="is-refundable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="is-reserved" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="is-super-package" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="drm-object" type="{http://localhost:8080/decoupling/schemas/common}drmObjectFullType" minOccurs="0"/>
 *         &lt;element name="penalty-charge" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="next-cycle-discount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="b2b-partner" type="{http://localhost:8080/decoupling/schemas/common}b2bPartnerFullType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface SubscriptionFullType {


    /**
     * Gets the value of the disallowCancellations property.
     * 
     */
    boolean isDisallowCancellations();

    /**
     * Sets the value of the disallowCancellations property.
     * 
     */
    void setDisallowCancellations(boolean value);

    /**
     * Gets the value of the b2BPartner property.
     * 
     * @return
     *     possible object is
     *     {@link com.vodafone.global.er.decoupling.binding.response.B2BPartnerFullType}
     */
    com.vodafone.global.er.decoupling.binding.response.B2BPartnerFullType getB2BPartner();

    /**
     * Sets the value of the b2BPartner property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.vodafone.global.er.decoupling.binding.response.B2BPartnerFullType}
     */
    void setB2BPartner(com.vodafone.global.er.decoupling.binding.response.B2BPartnerFullType value);

    /**
     * Gets the value of the nextCycleDiscount property.
     * 
     */
    double getNextCycleDiscount();

    /**
     * Sets the value of the nextCycleDiscount property.
     * 
     */
    void setNextCycleDiscount(double value);

    /**
     * Gets the value of the isSuperPackage property.
     * 
     */
    boolean isIsSuperPackage();

    /**
     * Sets the value of the isSuperPackage property.
     * 
     */
    void setIsSuperPackage(boolean value);

    /**
     * Gets the value of the superCreditBalances property.
     * 
     * @return
     *     possible object is
     *     {@link com.vodafone.global.er.decoupling.binding.response.SubscriptionFullType.SuperCreditBalancesType}
     */
    com.vodafone.global.er.decoupling.binding.response.SubscriptionFullType.SuperCreditBalancesType getSuperCreditBalances();

    /**
     * Sets the value of the superCreditBalances property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.vodafone.global.er.decoupling.binding.response.SubscriptionFullType.SuperCreditBalancesType}
     */
    void setSuperCreditBalances(com.vodafone.global.er.decoupling.binding.response.SubscriptionFullType.SuperCreditBalancesType value);

    /**
     * Gets the value of the transactions property.
     * 
     * @return
     *     possible object is
     *     {@link com.vodafone.global.er.decoupling.binding.response.SubscriptionFullType.TransactionsType}
     */
    com.vodafone.global.er.decoupling.binding.response.SubscriptionFullType.TransactionsType getTransactions();

    /**
     * Sets the value of the transactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.vodafone.global.er.decoupling.binding.response.SubscriptionFullType.TransactionsType}
     */
    void setTransactions(com.vodafone.global.er.decoupling.binding.response.SubscriptionFullType.TransactionsType value);

    /**
     * Gets the value of the translatedSuperCreditName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getTranslatedSuperCreditName();

    /**
     * Sets the value of the translatedSuperCreditName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setTranslatedSuperCreditName(java.lang.String value);

    /**
     * Gets the value of the hasExpired property.
     * 
     */
    boolean isHasExpired();

    /**
     * Sets the value of the hasExpired property.
     * 
     */
    void setHasExpired(boolean value);

    /**
     * Gets the value of the localPurchaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.util.Calendar}
     */
    java.util.Calendar getLocalPurchaseDate();

    /**
     * Sets the value of the localPurchaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.util.Calendar}
     */
    void setLocalPurchaseDate(java.util.Calendar value);

    /**
     * Gets the value of the purchaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.util.Calendar}
     */
    java.util.Calendar getPurchaseDate();

    /**
     * Sets the value of the purchaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.util.Calendar}
     */
    void setPurchaseDate(java.util.Calendar value);

    /**
     * Gets the value of the ratingAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link com.vodafone.global.er.decoupling.binding.response.RatingAttributesFullType}
     */
    com.vodafone.global.er.decoupling.binding.response.RatingAttributesFullType getRatingAttributes();

    /**
     * Sets the value of the ratingAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.vodafone.global.er.decoupling.binding.response.RatingAttributesFullType}
     */
    void setRatingAttributes(com.vodafone.global.er.decoupling.binding.response.RatingAttributesFullType value);

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.util.Calendar}
     */
    java.util.Calendar getStartDate();

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.util.Calendar}
     */
    void setStartDate(java.util.Calendar value);

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link com.vodafone.global.er.decoupling.binding.response.SubscriptionFullType.ServicesType}
     */
    com.vodafone.global.er.decoupling.binding.response.SubscriptionFullType.ServicesType getServices();

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.vodafone.global.er.decoupling.binding.response.SubscriptionFullType.ServicesType}
     */
    void setServices(com.vodafone.global.er.decoupling.binding.response.SubscriptionFullType.ServicesType value);

    /**
     * Gets the value of the package property.
     * 
     * @return
     *     possible object is
     *     {@link com.vodafone.global.er.decoupling.binding.response.CatalogPackageFullType}
     */
    com.vodafone.global.er.decoupling.binding.response.CatalogPackageFullType getPackage();

    /**
     * Sets the value of the package property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.vodafone.global.er.decoupling.binding.response.CatalogPackageFullType}
     */
    void setPackage(com.vodafone.global.er.decoupling.binding.response.CatalogPackageFullType value);

    /**
     * Gets the value of the isRecurring property.
     * 
     */
    boolean isIsRecurring();

    /**
     * Sets the value of the isRecurring property.
     * 
     */
    void setIsRecurring(boolean value);

    /**
     * Gets the value of the currentNumberOfOccurences property.
     * 
     */
    int getCurrentNumberOfOccurences();

    /**
     * Sets the value of the currentNumberOfOccurences property.
     * 
     */
    void setCurrentNumberOfOccurences(int value);

    /**
     * Gets the value of the isPreordered property.
     * 
     */
    boolean isIsPreordered();

    /**
     * Sets the value of the isPreordered property.
     * 
     */
    void setIsPreordered(boolean value);

    /**
     * Gets the value of the hasValidMicroService property.
     * 
     */
    boolean isHasValidMicroService();

    /**
     * Sets the value of the hasValidMicroService property.
     * 
     */
    void setHasValidMicroService(boolean value);

    /**
     * Gets the value of the penaltyCharge property.
     * 
     */
    double getPenaltyCharge();

    /**
     * Sets the value of the penaltyCharge property.
     * 
     */
    void setPenaltyCharge(double value);

    /**
     * Gets the value of the isRefundable property.
     * 
     */
    boolean isIsRefundable();

    /**
     * Sets the value of the isRefundable property.
     * 
     */
    void setIsRefundable(boolean value);

    /**
     * Gets the value of the translatedStatus property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getTranslatedStatus();

    /**
     * Sets the value of the translatedStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setTranslatedStatus(java.lang.String value);

    /**
     * Gets the value of the status property.
     * 
     */
    int getStatus();

    /**
     * Sets the value of the status property.
     * 
     */
    void setStatus(int value);

    /**
     * Gets the value of the resourceBalances property.
     * 
     * @return
     *     possible object is
     *     {@link com.vodafone.global.er.decoupling.binding.response.SubscriptionFullType.ResourceBalancesType}
     */
    com.vodafone.global.er.decoupling.binding.response.SubscriptionFullType.ResourceBalancesType getResourceBalances();

    /**
     * Sets the value of the resourceBalances property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.vodafone.global.er.decoupling.binding.response.SubscriptionFullType.ResourceBalancesType}
     */
    void setResourceBalances(com.vodafone.global.er.decoupling.binding.response.SubscriptionFullType.ResourceBalancesType value);

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.util.Calendar}
     */
    java.util.Calendar getExpiryDate();

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.util.Calendar}
     */
    void setExpiryDate(java.util.Calendar value);

    /**
     * Gets the value of the superCreditId property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getSuperCreditId();

    /**
     * Sets the value of the superCreditId property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setSuperCreditId(java.lang.String value);

    /**
     * Gets the value of the drmObject property.
     * 
     * @return
     *     possible object is
     *     {@link com.vodafone.global.er.decoupling.binding.response.DrmObjectFullType}
     */
    com.vodafone.global.er.decoupling.binding.response.DrmObjectFullType getDrmObject();

    /**
     * Sets the value of the drmObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.vodafone.global.er.decoupling.binding.response.DrmObjectFullType}
     */
    void setDrmObject(com.vodafone.global.er.decoupling.binding.response.DrmObjectFullType value);

    /**
     * Gets the value of the finalMinSubscriptionEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.util.Calendar}
     */
    java.util.Calendar getFinalMinSubscriptionEndDate();

    /**
     * Sets the value of the finalMinSubscriptionEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.util.Calendar}
     */
    void setFinalMinSubscriptionEndDate(java.util.Calendar value);

    /**
     * Gets the value of the localExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.util.Calendar}
     */
    java.util.Calendar getLocalExpiryDate();

    /**
     * Sets the value of the localExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.util.Calendar}
     */
    void setLocalExpiryDate(java.util.Calendar value);

    /**
     * Gets the value of the localStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.util.Calendar}
     */
    java.util.Calendar getLocalStartDate();

    /**
     * Sets the value of the localStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.util.Calendar}
     */
    void setLocalStartDate(java.util.Calendar value);

    /**
     * Gets the value of the minSubscriptionPeriodElapsed property.
     * 
     */
    boolean isMinSubscriptionPeriodElapsed();

    /**
     * Sets the value of the minSubscriptionPeriodElapsed property.
     * 
     */
    void setMinSubscriptionPeriodElapsed(boolean value);

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getId();

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setId(java.lang.String value);

    /**
     * Gets the value of the isReserved property.
     * 
     */
    boolean isIsReserved();

    /**
     * Sets the value of the isReserved property.
     * 
     */
    void setIsReserved(boolean value);

    /**
     * Gets the value of the overdueExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.util.Calendar}
     */
    java.util.Calendar getOverdueExpiryDate();

    /**
     * Sets the value of the overdueExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.util.Calendar}
     */
    void setOverdueExpiryDate(java.util.Calendar value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/matt/workspace/manifest-work/us/dev/er_core_batch/working/DECOUPLING_common/schemas/common/pa_common.xsd line 1258)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="resource-balance" type="{http://localhost:8080/decoupling/schemas/common}resourceBalanceFullType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ResourceBalancesType {


        /**
         * Gets the value of the ResourceBalance property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ResourceBalance property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResourceBalance().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.vodafone.global.er.decoupling.binding.response.ResourceBalanceFullType}
         * 
         */
        java.util.List getResourceBalance();

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/matt/workspace/manifest-work/us/dev/er_core_batch/working/DECOUPLING_common/schemas/common/pa_common.xsd line 1296)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="service-id" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ServicesType {


        /**
         * Gets the value of the ServiceId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ServiceId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getServiceId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link java.lang.String}
         * 
         */
        java.util.List getServiceId();

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/matt/workspace/manifest-work/us/dev/er_core_batch/working/DECOUPLING_common/schemas/common/pa_common.xsd line 1285)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="resource-balance" type="{http://localhost:8080/decoupling/schemas/common}resourceBalanceFullType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface SuperCreditBalancesType {


        /**
         * Gets the value of the ResourceBalance property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ResourceBalance property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResourceBalance().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.vodafone.global.er.decoupling.binding.response.ResourceBalanceFullType}
         * 
         */
        java.util.List getResourceBalance();

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/matt/workspace/manifest-work/us/dev/er_core_batch/working/DECOUPLING_common/schemas/common/pa_common.xsd line 1275)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="transaction" type="{http://localhost:8080/decoupling/schemas/common}transactionFullType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface TransactionsType {


        /**
         * Gets the value of the Transaction property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the Transaction property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTransaction().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.vodafone.global.er.decoupling.binding.response.TransactionFullType}
         * 
         */
        java.util.List getTransaction();

    }

}
